version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
environment:
  nodejs_version: 8
install:
- ps: Install-Product node $env:nodejs_version
- npm install
build_script:
- npm run build
artifacts:
- path: dist\
  name: web-app
deploy:
- provider: WebDeploy
  server: hgv-tango.scm.azurewebsites.net:443
  website: hgv-tango
  username: $hgv-tango
  password:
    secure: arRQ8kTlBOnoiTnbSRPJWKPlkO1KyA8P1d/xkCcW0eoFuajKhF2XOwWkIEeoPnGM/SSVYGhZjx3d5Cs60VLCYg==
  artifact: web-app
  remove_files: true